/**
 * Business Bottleneck Audit™ (BBA™) — Registry (DATA ONLY)
 * ---------------------------------------------------------------------------
 * The single source of truth for the 15 approved BBA categories and their
 * questions, transcribed verbatim from the approved BBA specification.
 *
 * NO invented questions. NO expanded scope. Adding a question later is one
 * new `BbaQuestion` entry below — never a schema or engine change.
 */

import { BBA_OWNERSHIP_OPTIONS, type BbaCategory, type BbaOption, type BbaQuestion } from "./types"

/* ===========================================================================
 * Categories — display order matches the approved spec's 15 categories.
 * ======================================================================== */

export const BBA_CATEGORIES: BbaCategory[] = [
  { id: "offer-product-service", name: "Offer / Product / Service", order: 1, hasOwnershipQuestion: true },
  { id: "marketing", name: "Marketing", order: 2, hasOwnershipQuestion: true },
  { id: "sales", name: "Sales", order: 3, hasOwnershipQuestion: true },
  { id: "client-delivery", name: "Client Delivery / Fulfillment", order: 4, hasOwnershipQuestion: true },
  { id: "team-employees", name: "Team / Employees", order: 5, hasOwnershipQuestion: true },
  { id: "founder-role-hats", name: "Founder Role / Hats", order: 6, hasOwnershipQuestion: false },
  { id: "systems-processes", name: "Systems / Processes", order: 7, hasOwnershipQuestion: true },
  { id: "ai-technology", name: "AI / Technology", order: 8, hasOwnershipQuestion: true },
  { id: "communication-leadership", name: "Communication / Leadership", order: 9, hasOwnershipQuestion: true },
  { id: "financial-economics", name: "Financial / Business Economics", order: 10, hasOwnershipQuestion: true },
  { id: "business-model-structure", name: "Business Model / Structure", order: 11, hasOwnershipQuestion: true },
  { id: "persistent-problems", name: "Persistent Problems / What I've Already Tried", order: 12, hasOwnershipQuestion: true },
  { id: "day-at-a-glance", name: "Your Day at a Glance™", order: 13, hasOwnershipQuestion: false },
  { id: "week-at-a-glance", name: "Your Week at a Glance™", order: 14, hasOwnershipQuestion: false },
  { id: "stakeholders-investors-reporting", name: "Stakeholders / Investors / Reporting", order: 15, hasOwnershipQuestion: true },
]

/* ===========================================================================
 * Shared option lists reused verbatim across questions per the spec's
 * "use the same selectable list" instructions.
 * ======================================================================== */

const YES_NO: BbaOption[] = [
  { id: "yes", label: "Yes" },
  { id: "no", label: "No" },
]

const YES_NO_SOMETIMES: BbaOption[] = [
  { id: "yes", label: "Yes" },
  { id: "no", label: "No" },
  { id: "sometimes", label: "Sometimes" },
]

const MARKETING_METHODS: BbaOption[] = [
  { id: "referrals", label: "Referrals" },
  { id: "networking", label: "Networking" },
  { id: "social-media", label: "Social Media" },
  { id: "content-marketing", label: "Content Marketing" },
  { id: "website-search", label: "Website / Search" },
  { id: "paid-advertising", label: "Paid Advertising" },
  { id: "email-marketing", label: "Email Marketing" },
  { id: "webinars", label: "Webinars" },
  { id: "challenges", label: "Challenges" },
  { id: "masterclasses", label: "Masterclasses" },
  { id: "jv-partners", label: "JV Partners / Collaborations" },
  { id: "speaking", label: "Speaking" },
  { id: "summits-intensives", label: "Summits / Intensives" },
  { id: "bootcamps-events", label: "Bootcamps / Events" },
  { id: "other", label: "Other", allowOtherText: true },
  { id: "not-currently-marketing", label: "I'm not currently marketing" },
]

const HATS: BbaOption[] = [
  { id: "ceo-founder", label: "CEO / Founder" },
  { id: "strategy-planning", label: "Strategy / Planning" },
  { id: "sales", label: "Sales" },
  { id: "marketing", label: "Marketing" },
  { id: "social-media", label: "Social Media" },
  { id: "content-creation", label: "Content Creation" },
  { id: "business-development-partnerships", label: "Business Development / Partnerships" },
  { id: "customer-service", label: "Customer Service" },
  { id: "client-delivery", label: "Client Delivery" },
  { id: "customer-success", label: "Customer Success" },
  { id: "operations", label: "Operations" },
  { id: "project-management", label: "Project Management" },
  { id: "team-management", label: "Team Management" },
  { id: "hiring-recruiting", label: "Hiring / Recruiting" },
  { id: "human-resources", label: "Human Resources" },
  { id: "finance-bookkeeping", label: "Finance / Bookkeeping" },
  { id: "administrative-work", label: "Administrative Work" },
  { id: "scheduling", label: "Scheduling" },
  { id: "technology-it", label: "Technology / IT" },
  { id: "systems-processes", label: "Systems / Processes" },
  { id: "ai-automation", label: "AI / Automation" },
  { id: "product-development", label: "Product Development" },
  { id: "service-development", label: "Service Development" },
  { id: "legal-compliance", label: "Legal / Compliance" },
  { id: "purchasing-vendors", label: "Purchasing / Vendors" },
  { id: "other", label: "Other", allowOtherText: true },
]

/* ===========================================================================
 * Questions — flat list, grouped by category, in spec order.
 * ======================================================================== */

export const BBA_QUESTIONS: BbaQuestion[] = [
  // ── 1. Offer / Product / Service ───────────────────────────────────────
  {
    id: "offer.hasOffer",
    categoryId: "offer-product-service",
    kind: "single-select",
    prompt: "Do you currently offer a product or service to clients/customers?",
    options: [
      { id: "product", label: "Product" },
      { id: "service", label: "Service" },
      { id: "both", label: "Both" },
      { id: "no", label: "No" },
      { id: "developing-one-now", label: "I'm developing one now" },
    ],
    order: 1,
    status: "active",
  },
  {
    id: "offer.madeSales",
    categoryId: "offer-product-service",
    kind: "single-select",
    prompt: "Have you made any sales?",
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" },
      { id: "inconsistent-sales", label: "I have made sales, but not consistently" },
    ],
    order: 2,
    status: "active",
  },
  {
    id: "offer.idealCustomer",
    categoryId: "offer-product-service",
    kind: "multi-select",
    prompt: "Who is your ideal customer/client?",
    helperText: "Give a few simple examples to aid comprehension.",
    options: [
      { id: "consumers", label: "Consumers" },
      { id: "entrepreneurs", label: "Entrepreneurs" },
      { id: "small-businesses", label: "Small businesses" },
      { id: "corporations", label: "Corporations" },
      { id: "nonprofits", label: "Nonprofits" },
      { id: "professionals", label: "Professionals" },
      { id: "organizations-institutions", label: "Organizations / Institutions" },
      { id: "other", label: "Other", allowOtherText: true },
      { id: "not-sure", label: "I'm not sure" },
    ],
    order: 3,
    status: "active",
  },
  {
    id: "offer.enoughInterest",
    categoryId: "offer-product-service",
    kind: "single-select",
    prompt: "Are you getting enough interest in your product or service from your ideal customers/clients?",
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" },
      { id: "inconsistently", label: "Inconsistently" },
      { id: "not-sure", label: "I'm not sure" },
    ],
    order: 4,
    status: "active",
  },
  {
    id: "offer.problem",
    categoryId: "offer-product-service",
    kind: "multi-select",
    prompt: "Is there anything about your product/service/offer that is currently a problem or concern?",
    options: [
      { id: "difficult-to-explain", label: "It's difficult to explain" },
      { id: "customers-dont-understand-value", label: "Customers don't understand the value" },
      { id: "difficult-to-differentiate", label: "It's difficult to differentiate" },
      { id: "pricing-concern", label: "Pricing is a concern" },
      { id: "too-time-consuming-to-deliver", label: "It's too time-consuming to deliver" },
      { id: "customize-too-much", label: "I customize too much" },
      { id: "too-many-offers", label: "I have too many offers" },
      { id: "not-sure-what-to-sell", label: "I'm not sure what to sell" },
      { id: "other", label: "Other", allowOtherText: true },
      { id: "none-of-these", label: "None of these" },
    ],
    order: 5,
    status: "active",
  },
  {
    id: "offer.ownership",
    categoryId: "offer-product-service",
    kind: "single-select",
    prompt: "Who currently owns the product/service/offer role?",
    options: BBA_OWNERSHIP_OPTIONS,
    order: 6,
    status: "active",
  },

  // ── 2. Marketing ─────────────────────────────────────────────────────────
  {
    id: "marketing.currentlyMarketing",
    categoryId: "marketing",
    kind: "single-select",
    prompt: "Are you currently marketing your business?",
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" },
      { id: "inconsistently", label: "Inconsistently" },
    ],
    order: 1,
    status: "active",
  },
  {
    id: "marketing.enoughInterest",
    categoryId: "marketing",
    kind: "single-select",
    prompt: "Are you getting enough interest in your product or service from the right people?",
    showIf: { questionId: "marketing.currentlyMarketing", equalsAny: ["yes", "inconsistently"] },
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" },
      { id: "inconsistently", label: "Inconsistently" },
      { id: "not-sure", label: "I'm not sure" },
    ],
    order: 2,
    status: "active",
  },
  {
    id: "marketing.methodsUsed",
    categoryId: "marketing",
    kind: "multi-select",
    prompt: "Which marketing methods are you currently using?",
    options: MARKETING_METHODS,
    order: 3,
    status: "active",
  },
  {
    id: "marketing.methodsProducing",
    categoryId: "marketing",
    kind: "multi-select",
    prompt: "Which of these are currently producing leads or customers?",
    helperText: "Use the same selectable list.",
    options: MARKETING_METHODS,
    order: 4,
    status: "active",
  },
  {
    id: "marketing.noMarketingBlocker",
    categoryId: "marketing",
    kind: "multi-select",
    prompt: "What is keeping you from marketing your business right now?",
    showIf: { questionId: "marketing.currentlyMarketing", equalsAny: ["no"] },
    options: [
      { id: "dont-know-where-to-start", label: "I don't know where to start" },
      { id: "not-enough-time", label: "I don't have enough time" },
      { id: "dont-know-what-to-say", label: "I don't know what to say" },
      { id: "dont-know-which-channels", label: "I don't know which channels to use" },
      { id: "no-marketing-system", label: "I don't have a marketing system" },
      { id: "feels-overwhelming", label: "Marketing feels overwhelming" },
      { id: "focused-on-other-priorities", label: "I'm focused on other business priorities" },
      { id: "other", label: "Other", allowOtherText: true },
    ],
    order: 5,
    status: "active",
  },
  {
    id: "marketing.weeklyClientEvent",
    categoryId: "marketing",
    kind: "single-select",
    prompt: "Do you have a weekly client connection event?",
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" },
      { id: "sometimes", label: "Sometimes" },
    ],
    order: 6,
    status: "active",
  },
  {
    id: "marketing.weeklyClientEventType",
    categoryId: "marketing",
    kind: "multi-select",
    prompt: "What type of weekly client connection event do you have?",
    showIf: { questionId: "marketing.weeklyClientEvent", equalsAny: ["yes"] },
    options: [
      { id: "client-qa", label: "Client Q&A" },
      { id: "community-call", label: "Community Call" },
      { id: "group-coaching", label: "Group Coaching" },
      { id: "workshop", label: "Workshop" },
      { id: "webinar", label: "Webinar" },
      { id: "masterclass", label: "Masterclass" },
      { id: "networking", label: "Networking" },
      { id: "office-hours", label: "Office Hours" },
      { id: "client-appreciation-connection-event", label: "Client Appreciation / Connection Event" },
      { id: "other", label: "Other", allowOtherText: true },
    ],
    order: 7,
    status: "active",
  },
  {
    id: "marketing.ownership",
    categoryId: "marketing",
    kind: "single-select",
    prompt: "Who currently owns the marketing role?",
    options: BBA_OWNERSHIP_OPTIONS,
    order: 8,
    status: "active",
  },

  // ── 3. Sales ─────────────────────────────────────────────────────────────
  {
    id: "sales.hasProcess",
    categoryId: "sales",
    kind: "single-select",
    prompt: "Do you currently have a sales process?",
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" },
      { id: "somewhat-inconsistently", label: "Somewhat / inconsistently" },
    ],
    order: 1,
    status: "active",
  },
  {
    id: "sales.stuckWhere",
    categoryId: "sales",
    kind: "multi-select",
    prompt: "Where does selling most often get stuck?",
    options: [
      { id: "finding-leads", label: "Finding leads" },
      { id: "getting-right-leads", label: "Getting the right leads" },
      { id: "qualifying-leads", label: "Qualifying leads" },
      { id: "getting-sales-conversation", label: "Getting the sales conversation" },
      { id: "making-offer-proposal", label: "Making the offer / proposal" },
      { id: "pricing", label: "Pricing" },
      { id: "negotiation", label: "Negotiation" },
      { id: "asking-for-sale", label: "Asking for the sale" },
      { id: "closing", label: "Closing" },
      { id: "following-up", label: "Following up" },
      { id: "not-sure", label: "I'm not sure" },
    ],
    order: 2,
    status: "active",
  },
  {
    id: "sales.dependsOnFounder",
    categoryId: "sales",
    kind: "single-select",
    prompt: "Does sales depend heavily on you?",
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" },
      { id: "partly", label: "Partly" },
    ],
    order: 3,
    status: "active",
  },
  {
    id: "sales.problem",
    categoryId: "sales",
    kind: "multi-select",
    prompt: "What is currently a sales problem or concern?",
    options: [
      { id: "not-enough-leads", label: "Not enough leads" },
      { id: "poor-quality-leads", label: "Poor-quality leads" },
      { id: "low-conversion", label: "Low conversion" },
      { id: "long-sales-cycle", label: "Long sales cycle" },
      { id: "inconsistent-follow-up", label: "Inconsistent follow-up" },
      { id: "pricing", label: "Pricing" },
      { id: "negotiation", label: "Negotiation" },
      { id: "closing", label: "Closing" },
      { id: "unpredictable-revenue", label: "Unpredictable revenue" },
      { id: "other", label: "Other", allowOtherText: true },
      { id: "none-of-these", label: "None of these" },
    ],
    order: 4,
    status: "active",
  },
  {
    id: "sales.ownership",
    categoryId: "sales",
    kind: "single-select",
    prompt: "Who currently owns the sales role?",
    options: BBA_OWNERSHIP_OPTIONS,
    order: 5,
    status: "active",
  },

  // ── 4. Client Delivery / Fulfillment ────────────────────────────────────
  {
    id: "delivery.hasProblem",
    categoryId: "client-delivery",
    kind: "single-select",
    prompt: "Is delivering what you sell currently creating any problems or concerns?",
    options: YES_NO_SOMETIMES,
    order: 1,
    status: "active",
  },
  {
    id: "delivery.whatHappening",
    categoryId: "client-delivery",
    kind: "multi-select",
    prompt: "What is happening?",
    showIf: { questionId: "delivery.hasProblem", equalsAny: ["yes", "sometimes"] },
    options: [
      { id: "takes-too-long", label: "It takes too long" },
      { id: "step-in-frequently", label: "I have to step in frequently" },
      { id: "clients-need-clarification", label: "Clients need too much clarification" },
      { id: "work-gets-redone", label: "Work gets redone" },
      { id: "scope-expands", label: "Scope expands" },
      { id: "handoffs-break-down", label: "Handoffs break down" },
      { id: "work-gets-delayed", label: "Work gets delayed" },
      { id: "inconsistent-client-experience", label: "The client experience is inconsistent" },
      { id: "difficult-to-scale", label: "It's difficult to scale" },
      { id: "other", label: "Other", allowOtherText: true },
      { id: "none-of-these", label: "None of these" },
    ],
    order: 2,
    status: "active",
  },
  {
    id: "delivery.ownership",
    categoryId: "client-delivery",
    kind: "single-select",
    prompt: "Who currently owns client delivery/fulfillment?",
    options: BBA_OWNERSHIP_OPTIONS,
    order: 3,
    status: "active",
  },

  // ── 5. Team / Employees ─────────────────────────────────────────────────
  {
    id: "team.hasTeam",
    categoryId: "team-employees",
    kind: "single-select",
    prompt: "Do you currently have a team or employees?",
    options: YES_NO,
    order: 1,
    status: "active",
  },
  {
    id: "team.size",
    categoryId: "team-employees",
    kind: "single-select",
    prompt: "How many people are currently on your team?",
    showIf: { questionId: "team.hasTeam", equalsAny: ["yes"] },
    options: [
      { id: "1", label: "1" },
      { id: "2-5", label: "2–5" },
      { id: "6-10", label: "6–10" },
      { id: "11-25", label: "11–25" },
      { id: "26-50", label: "26–50" },
      { id: "51-100", label: "51–100" },
      { id: "more-than-100", label: "More than 100" },
    ],
    order: 2,
    status: "active",
  },
  {
    id: "team.whoWorks",
    categoryId: "team-employees",
    kind: "multi-select",
    prompt: "Who works in your business?",
    showIf: { questionId: "team.hasTeam", equalsAny: ["yes"] },
    options: [
      { id: "employees", label: "Employees" },
      { id: "contractors", label: "Contractors" },
      { id: "freelancers", label: "Freelancers" },
      { id: "virtual-assistants", label: "Virtual Assistants" },
      { id: "partners", label: "Partners" },
      { id: "other", label: "Other", allowOtherText: true },
    ],
    order: 3,
    status: "active",
  },
  {
    id: "team.problem",
    categoryId: "team-employees",
    kind: "multi-select",
    prompt: "What is currently a team/people problem or concern?",
    options: [
      { id: "roles-not-clear", label: "Roles aren't clear" },
      { id: "ownership-not-clear", label: "Ownership isn't clear" },
      { id: "too-many-decisions-to-me", label: "Too many decisions come to me" },
      { id: "people-wait-for-approval", label: "People wait for my approval" },
      { id: "work-comes-back-to-me", label: "Work comes back to me" },
      { id: "accountability-unclear", label: "Accountability is unclear" },
      { id: "not-enough-information", label: "People don't have enough information" },
      { id: "team-communication-problem", label: "Team communication is a problem" },
      { id: "need-more-training", label: "Team members need more training" },
      { id: "need-to-hire", label: "I need to hire" },
      { id: "may-need-better-systems-before-hiring", label: "I may need better systems before hiring" },
      { id: "other", label: "Other", allowOtherText: true },
      { id: "none-of-these", label: "None of these" },
    ],
    order: 4,
    status: "active",
  },
  {
    id: "team.ownership",
    categoryId: "team-employees",
    kind: "single-select",
    prompt: "Who currently owns the team/people role?",
    options: BBA_OWNERSHIP_OPTIONS,
    order: 5,
    status: "active",
  },

  // ── 6. Founder Role / Hats ───────────────────────────────────────────────
  {
    id: "founder.wearsTooManyHats",
    categoryId: "founder-role-hats",
    kind: "single-select",
    // DO NOT REPHRASE — exact wording required by the approved spec.
    prompt: "I wear too many or all the hats in my business.",
    options: YES_NO_SOMETIMES,
    order: 1,
    status: "active",
  },
  {
    id: "founder.hatsWorn",
    categoryId: "founder-role-hats",
    kind: "multi-select",
    prompt: "Which hats are you currently wearing?",
    options: HATS,
    order: 2,
    status: "active",
  },
  {
    id: "founder.hatsOwned",
    categoryId: "founder-role-hats",
    kind: "multi-select",
    prompt: "Which roles do you currently own?",
    helperText: "Use the same role list.",
    options: HATS,
    order: 3,
    status: "active",
  },

  // ── 7. Systems / Processes ──────────────────────────────────────────────
  {
    id: "systems.hasRepeatable",
    categoryId: "systems-processes",
    kind: "single-select",
    prompt: "Do you have repeatable systems or processes for important recurring work?",
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" },
      { id: "some", label: "Some" },
    ],
    order: 1,
    status: "active",
  },
  {
    id: "systems.problem",
    categoryId: "systems-processes",
    kind: "multi-select",
    prompt: "What is currently a problem or concern?",
    options: [
      { id: "processes-in-my-head", label: "Important processes are in my head" },
      { id: "work-repeated-manually", label: "Work is repeated manually" },
      { id: "reinvent-the-wheel", label: "We reinvent the wheel" },
      { id: "things-get-forgotten", label: "Things get forgotten" },
      { id: "handoffs-break-down", label: "Handoffs break down" },
      { id: "too-much-manual-coordination", label: "Too much coordination is manual" },
      { id: "too-many-tools", label: "We have too many tools" },
      { id: "information-difficult-to-find", label: "Information is difficult to find" },
      { id: "systems-dont-work-together", label: "Systems don't work together" },
      { id: "people-dont-follow-processes", label: "People don't consistently follow processes" },
      { id: "other", label: "Other", allowOtherText: true },
      { id: "none-of-these", label: "None of these" },
    ],
    order: 2,
    status: "active",
  },
  {
    id: "systems.unavailableImpact",
    categoryId: "systems-processes",
    kind: "multi-select",
    prompt: "If you were unavailable for two weeks, what would be affected?",
    options: [
      { id: "sales", label: "Sales" },
      { id: "marketing", label: "Marketing" },
      { id: "client-delivery", label: "Client delivery" },
      { id: "team-decisions", label: "Team decisions" },
      { id: "operations", label: "Operations" },
      { id: "most-of-the-business", label: "Most of the business" },
      { id: "very-little", label: "Very little" },
      { id: "not-sure", label: "I'm not sure" },
    ],
    order: 3,
    status: "active",
  },
  {
    id: "systems.ownership",
    categoryId: "systems-processes",
    kind: "single-select",
    prompt: "Who currently owns the systems/process role?",
    options: BBA_OWNERSHIP_OPTIONS,
    order: 4,
    status: "active",
  },

  // ── 8. AI / Technology ───────────────────────────────────────────────────
  {
    id: "ai.currentState",
    categoryId: "ai-technology",
    kind: "multi-select",
    prompt: "What is AI currently doing in your business?",
    options: [
      { id: "research", label: "Research" },
      { id: "writing-drafting", label: "Writing / Drafting" },
      { id: "content", label: "Content" },
      { id: "marketing", label: "Marketing" },
      { id: "sales", label: "Sales" },
      { id: "lead-qualification", label: "Lead Qualification" },
      { id: "follow-up", label: "Follow-up" },
      { id: "customer-communication", label: "Customer Communication" },
      { id: "customer-support", label: "Customer Support" },
      { id: "meeting-prep-notes", label: "Meeting Preparation / Notes" },
      { id: "analysis-reporting", label: "Analysis / Reporting" },
      { id: "administration", label: "Administration" },
      { id: "documentation", label: "Documentation" },
      { id: "client-onboarding", label: "Client Onboarding" },
      { id: "client-delivery", label: "Client Delivery" },
      { id: "workflow-automation", label: "Workflow Automation" },
      { id: "information-management", label: "Information Management" },
      { id: "ai-agents-workflows", label: "AI Agents / AI Workflows" },
      { id: "nothing-yet", label: "Nothing yet" },
      { id: "not-sure", label: "I'm not sure" },
    ],
    order: 1,
    status: "active",
  },
  {
    id: "ai.gap",
    categoryId: "ai-technology",
    kind: "multi-select",
    prompt: "Where is AI NOT currently helping, but you believe it could?",
    options: [
      { id: "research", label: "Research" },
      { id: "marketing", label: "Marketing" },
      { id: "sales", label: "Sales" },
      { id: "follow-up", label: "Follow-up" },
      { id: "customer-support", label: "Customer Support" },
      { id: "reporting-analysis", label: "Reporting / Analysis" },
      { id: "administration", label: "Administration" },
      { id: "documentation", label: "Documentation" },
      { id: "client-onboarding", label: "Client Onboarding" },
      { id: "client-delivery", label: "Client Delivery" },
      { id: "workflow-automation", label: "Workflow Automation" },
      { id: "information-management", label: "Information Management" },
      { id: "repetitive-work", label: "Repetitive Work" },
      { id: "decision-support", label: "Decision Support" },
      { id: "other", label: "Other", allowOtherText: true },
      { id: "not-sure", label: "I'm not sure" },
    ],
    order: 2,
    status: "active",
  },
  {
    id: "ai.blockers",
    categoryId: "ai-technology",
    kind: "multi-select",
    prompt: "What is preventing you from using AI there?",
    options: [
      { id: "dont-know-how", label: "I don't know how" },
      { id: "dont-know-which-tools", label: "I don't know which tools to use" },
      { id: "dont-know-how-to-build-workflow", label: "I don't know how to build the workflow" },
      { id: "processes-not-clear", label: "My processes aren't clear" },
      { id: "information-not-organized", label: "My information isn't organized" },
      { id: "dont-trust-ai-yet", label: "I don't trust AI with the work yet" },
      { id: "privacy-security-concerns", label: "Privacy / Security concerns" },
      { id: "tried-ai-didnt-work", label: "I tried AI and it didn't work" },
      { id: "too-many-tools", label: "I have too many tools" },
      { id: "no-time-to-implement", label: "I don't have time to implement it" },
      { id: "dont-know-if-ai-is-right-solution", label: "I don't know whether AI is the right solution" },
      { id: "nothing", label: "Nothing" },
    ],
    order: 3,
    status: "active",
  },
  {
    id: "ai.agentOpportunity",
    categoryId: "ai-technology",
    kind: "multi-select",
    prompt: "Where could an AI agent potentially help?",
    options: [
      { id: "research", label: "Research" },
      { id: "sales", label: "Sales" },
      { id: "marketing", label: "Marketing" },
      { id: "customer-support", label: "Customer Support" },
      { id: "client-onboarding", label: "Client Onboarding" },
      { id: "reporting", label: "Reporting" },
      { id: "knowledge-management", label: "Knowledge Management" },
      { id: "workflow-coordination", label: "Workflow Coordination" },
      { id: "monitoring", label: "Monitoring" },
      { id: "other", label: "Other", allowOtherText: true },
      { id: "dont-know", label: "I don't know" },
    ],
    order: 4,
    status: "active",
  },
  {
    id: "ai.ownership",
    categoryId: "ai-technology",
    kind: "single-select",
    prompt: "Who currently owns the AI / technology role?",
    options: BBA_OWNERSHIP_OPTIONS,
    order: 5,
    status: "active",
  },

  // ── 9. Communication / Leadership ───────────────────────────────────────
  {
    id: "communication.hasProblem",
    categoryId: "communication-leadership",
    kind: "single-select",
    prompt: "Is communication currently creating problems in your business?",
    options: YES_NO_SOMETIMES,
    order: 1,
    status: "active",
  },
  {
    id: "communication.whatHappening",
    categoryId: "communication-leadership",
    kind: "multi-select",
    prompt: "What is happening?",
    showIf: { questionId: "communication.hasProblem", equalsAny: ["yes", "sometimes"] },
    options: [
      { id: "message-not-clear", label: "My message isn't clear" },
      { id: "team-priorities-not-clear", label: "Team priorities aren't clear" },
      { id: "expectations-not-clear", label: "Expectations aren't clear" },
      { id: "repeat-myself", label: "I have to repeat myself" },
      { id: "difficult-conversations-avoided", label: "Difficult conversations are being avoided" },
      { id: "clients-misunderstand-expectations", label: "Clients misunderstand expectations" },
      { id: "struggle-to-explain-value", label: "I struggle to explain our value" },
      { id: "struggle-to-ask-for-sale", label: "I struggle to ask for the sale" },
      { id: "negotiations-difficult", label: "Negotiations are difficult" },
      { id: "difficulty-articulating-ideas", label: "I have difficulty articulating my ideas" },
      { id: "decisions-not-communicated-clearly", label: "Important decisions aren't communicated clearly" },
      { id: "other", label: "Other", allowOtherText: true },
      { id: "none-of-these", label: "None of these" },
    ],
    order: 2,
    status: "active",
  },
  {
    id: "communication.ownership",
    categoryId: "communication-leadership",
    kind: "single-select",
    prompt: "Who currently owns the communication/leadership role?",
    options: BBA_OWNERSHIP_OPTIONS,
    order: 3,
    status: "active",
  },

  // ── 10. Financial / Business Economics ──────────────────────────────────
  {
    id: "financial.hasProblem",
    categoryId: "financial-economics",
    kind: "single-select",
    prompt: "Is the financial side of the business currently creating a problem or concern?",
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" },
      { id: "not-sure", label: "I'm not sure" },
    ],
    order: 1,
    status: "active",
  },
  {
    id: "financial.concern",
    categoryId: "financial-economics",
    kind: "multi-select",
    prompt: "What is the concern?",
    showIf: { questionId: "financial.hasProblem", equalsAny: ["yes"] },
    options: [
      { id: "revenue-too-low", label: "Revenue is too low" },
      { id: "revenue-unpredictable", label: "Revenue is unpredictable" },
      { id: "profit-too-low", label: "Profit is too low" },
      { id: "margins-too-low", label: "Margins are too low" },
      { id: "pricing-too-low", label: "Pricing may be too low" },
      { id: "cash-flow", label: "Cash flow" },
      { id: "customers-take-too-long-to-pay", label: "Customers take too long to pay" },
      { id: "customers-not-profitable-enough", label: "Some customers aren't profitable enough" },
      { id: "work-takes-too-much-time-for-revenue", label: "Some work takes too much time for the revenue it produces" },
      { id: "costs-too-high", label: "Costs are too high" },
      { id: "dont-know-most-profitable", label: "I don't know which offers/customers are most profitable" },
      { id: "other", label: "Other", allowOtherText: true },
      { id: "none-of-these", label: "None of these" },
    ],
    order: 2,
    status: "active",
  },
  {
    id: "financial.ownership",
    categoryId: "financial-economics",
    kind: "single-select",
    prompt: "Who currently owns the financial/business economics role?",
    options: BBA_OWNERSHIP_OPTIONS,
    order: 3,
    status: "active",
  },

  // ── 11. Business Model / Structure ──────────────────────────────────────
  {
    id: "businessModel.hasProblem",
    categoryId: "business-model-structure",
    kind: "single-select",
    prompt: "Is there anything about the way your business is structured that is making it harder to operate the way you want?",
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" },
      { id: "not-sure", label: "I'm not sure" },
    ],
    order: 1,
    status: "active",
  },
  {
    id: "businessModel.problem",
    categoryId: "business-model-structure",
    kind: "multi-select",
    prompt: "What is creating the problem?",
    showIf: { questionId: "businessModel.hasProblem", equalsAny: ["yes"] },
    options: [
      { id: "too-many-offers", label: "Too many offers" },
      { id: "too-much-customization", label: "Too much customization" },
      { id: "too-much-founder-involvement", label: "Too much founder involvement" },
      { id: "too-much-complexity", label: "Too much complexity" },
      { id: "one-person-critical", label: "One person is critical to the business" },
      { id: "one-customer-critical", label: "One customer is critical to the business" },
      { id: "one-channel-critical", label: "One channel is critical to the business" },
      { id: "delivery-model-too-much-work", label: "Delivery model creates too much work" },
      { id: "pricing-model-creates-problems", label: "Pricing model creates problems" },
      { id: "growth-creates-more-work-than-capacity", label: "Growth creates more work than capacity" },
      { id: "growth-would-worsen-work-life-balance", label: "Growth would make my work-life balance worse" },
      { id: "other", label: "Other", allowOtherText: true },
      { id: "none-of-these", label: "None of these" },
    ],
    order: 2,
    status: "active",
  },
  {
    id: "businessModel.ownership",
    categoryId: "business-model-structure",
    kind: "single-select",
    prompt: "Who currently owns the business model/structure role?",
    options: BBA_OWNERSHIP_OPTIONS,
    order: 3,
    status: "active",
  },

  // ── 12. Persistent Problems / What I've Already Tried ───────────────────
  {
    id: "persistent.hasRecurringProblem",
    categoryId: "persistent-problems",
    kind: "single-select",
    prompt: "Is there a business problem that keeps happening?",
    options: YES_NO,
    order: 1,
    status: "active",
  },
  {
    id: "persistent.whatTried",
    categoryId: "persistent-problems",
    kind: "multi-select",
    prompt: "What have you already tried?",
    showIf: { questionId: "persistent.hasRecurringProblem", equalsAny: ["yes"] },
    options: [
      { id: "created-a-process", label: "Created a process" },
      { id: "delegated-it", label: "Delegated it" },
      { id: "hired-someone", label: "Hired someone" },
      { id: "added-a-tool", label: "Added a tool" },
      { id: "added-automation", label: "Added automation" },
      { id: "tried-ai", label: "Tried AI" },
      { id: "changed-the-offer", label: "Changed the offer" },
      { id: "changed-marketing", label: "Changed marketing" },
      { id: "changed-pricing", label: "Changed pricing" },
      { id: "added-meetings", label: "Added meetings" },
      { id: "other", label: "Other", allowOtherText: true },
      { id: "nothing-yet", label: "Nothing yet" },
    ],
    order: 2,
    status: "active",
  },
  {
    id: "persistent.whatHappened",
    categoryId: "persistent-problems",
    kind: "single-select",
    prompt: "What happened?",
    showIf: { questionId: "persistent.hasRecurringProblem", equalsAny: ["yes"] },
    options: [
      { id: "it-worked", label: "It worked" },
      { id: "it-worked-temporarily", label: "It worked temporarily" },
      { id: "it-didnt-work", label: "It didn't work" },
      { id: "it-created-another-problem", label: "It created another problem" },
      { id: "not-sure-why-it-didnt-stick", label: "I'm not sure why it didn't stick" },
    ],
    order: 3,
    status: "active",
  },
  {
    id: "persistent.ownership",
    categoryId: "persistent-problems",
    kind: "single-select",
    prompt: "Who currently owns the problem or area where the problem occurs?",
    showIf: { questionId: "persistent.hasRecurringProblem", equalsAny: ["yes"] },
    options: BBA_OWNERSHIP_OPTIONS,
    order: 4,
    status: "active",
  },

  // ── 13. Your Day at a Glance™ ────────────────────────────────────────────
  {
    id: "day.wakeWithBirds",
    categoryId: "day-at-a-glance",
    kind: "single-select",
    prompt: "I wake up with the birds.",
    options: YES_NO_SOMETIMES,
    order: 1,
    status: "active",
  },
  {
    id: "day.wakeTime",
    categoryId: "day-at-a-glance",
    kind: "time",
    prompt: "What time do you usually wake up?",
    order: 2,
    status: "active",
  },
  {
    id: "day.sleepHours",
    categoryId: "day-at-a-glance",
    kind: "number",
    prompt: "I sleep approximately ___ hours a night.",
    order: 3,
    status: "active",
  },
  {
    id: "day.lunchHabit",
    categoryId: "day-at-a-glance",
    kind: "single-select",
    prompt: "Do you usually skip lunch, eat on the run, or eat at your desk?",
    options: [
      { id: "skip-lunch", label: "I skip lunch" },
      { id: "eat-on-the-run", label: "I eat on the run" },
      { id: "eat-at-my-desk", label: "I eat at my desk" },
      { id: "take-a-real-lunch-break", label: "I take a real lunch break" },
      { id: "it-varies", label: "It varies" },
    ],
    order: 4,
    status: "active",
  },
  {
    id: "day.homeForDinner",
    categoryId: "day-at-a-glance",
    kind: "single-select",
    prompt: "Are you usually home in time for dinner?",
    options: YES_NO_SOMETIMES,
    order: 5,
    status: "active",
  },
  {
    id: "day.exerciseBeforeWork",
    categoryId: "day-at-a-glance",
    kind: "single-select",
    prompt: "Do you exercise before your workday?",
    options: YES_NO_SOMETIMES,
    order: 6,
    status: "active",
  },
  {
    id: "day.typicalWorkday",
    categoryId: "day-at-a-glance",
    kind: "multi-select",
    prompt: "During a typical workday, which of these are true?",
    options: [
      { id: "start-reacting-to-messages", label: "I start by reacting to messages" },
      { id: "start-without-clear-priority", label: "I start without a clear priority" },
      { id: "interrupted-frequently", label: "I get interrupted frequently" },
      { id: "jump-between-tasks", label: "I jump between tasks" },
      { id: "too-many-meetings", label: "I have too many meetings" },
      { id: "answer-team-questions-all-day", label: "I answer team questions throughout the day" },
      { id: "approve-too-many-decisions", label: "I approve too many decisions" },
      { id: "do-work-someone-else-could-own", label: "I do work someone else could own" },
      { id: "repetitive-admin-work", label: "I do repetitive administrative work" },
      { id: "fix-recurring-problems", label: "I fix recurring problems" },
      { id: "urgent-work-takes-over", label: "Urgent work takes over" },
      { id: "strategic-work-pushed-aside", label: "Strategic work gets pushed aside" },
      { id: "work-beyond-intended-workday", label: "I work beyond my intended workday" },
      { id: "carry-business-work-into-personal-time", label: "I carry business work into personal time" },
      { id: "busy-without-moving-business-forward", label: "I am busy without moving the business forward" },
      { id: "have-protected-ceo-focus-time", label: "I have protected CEO focus time" },
      { id: "know-priority-before-focused-work", label: "I know my priority before focused work" },
      { id: "spend-meaningful-time-building-business", label: "I spend meaningful time building the business" },
    ],
    order: 7,
    status: "active",
  },
  {
    id: "day.ownership",
    categoryId: "day-at-a-glance",
    kind: "single-select",
    prompt: "Who currently owns your workday?",
    options: [
      { id: "i-own-it", label: "I own it" },
      { id: "someone-else-controls-most-of-my-day", label: "Someone else controls most of my day" },
      { id: "shared", label: "It is shared" },
      { id: "not-sure", label: "I'm not sure" },
    ],
    order: 8,
    status: "active",
  },

  // ── 14. Your Week at a Glance™ ───────────────────────────────────────────
  {
    id: "week.typicalWeek",
    categoryId: "week-at-a-glance",
    kind: "multi-select",
    prompt: "During a typical week, which of these are true?",
    options: [
      { id: "too-much-time-in-meetings", label: "Too much time in meetings" },
      { id: "too-much-administration", label: "Too much administration" },
      { id: "too-much-problem-solving", label: "Too much problem-solving" },
      { id: "too-much-client-delivery", label: "Too much client delivery" },
      { id: "too-much-people-management", label: "Too much people management" },
      { id: "too-much-correcting-reworking", label: "Too much correcting / reworking" },
      { id: "too-much-marketing", label: "Too much marketing" },
      { id: "too-much-selling", label: "Too much selling" },
      { id: "too-little-strategy", label: "Too little strategy" },
      { id: "too-little-business-building", label: "Too little business building" },
      { id: "too-little-ceo-decision-making", label: "Too little CEO decision-making" },
      { id: "too-little-systems-work", label: "Too little systems work" },
      { id: "too-little-revenue-generating-work", label: "Too little revenue-generating work" },
      { id: "priorities-change-frequently", label: "Priorities change frequently" },
      { id: "work-carries-into-next-week", label: "Work carries into the next week" },
      { id: "work-outside-intended-hours", label: "I work outside my intended hours" },
      { id: "work-weekends", label: "I work weekends" },
      { id: "same-bottleneck-repeatedly", label: "The same bottleneck appears repeatedly" },
      { id: "business-depends-heavily-on-me", label: "The business depends heavily on me" },
      { id: "not-enough-protected-ceo-time", label: "I don't have enough protected CEO time" },
      { id: "week-feels-reactive", label: "My week feels reactive" },
      { id: "business-would-struggle-if-stepped-away", label: "My business would struggle if I stepped away for two weeks" },
      { id: "priorities-remain-stable", label: "My priorities remain stable" },
      { id: "important-work-moves-forward-every-week", label: "Important work moves forward every week" },
      { id: "team-can-operate-without-me", label: "My team can operate without me" },
    ],
    order: 1,
    status: "active",
  },
  {
    id: "week.ownership",
    categoryId: "week-at-a-glance",
    kind: "single-select",
    prompt: "Who currently owns the overall running of your business week?",
    options: [
      { id: "i-own-it", label: "I own it" },
      { id: "someone-else-owns-most-of-it", label: "Someone else owns most of it" },
      { id: "shared", label: "It is shared" },
      { id: "no-one-owns-it", label: "No one clearly owns it" },
    ],
    order: 2,
    status: "active",
  },

  // ── 15. Stakeholders / Investors / Reporting ────────────────────────────
  {
    id: "stakeholders.types",
    categoryId: "stakeholders-investors-reporting",
    kind: "multi-select",
    prompt: "Do you currently have business stakeholders you are accountable to?",
    options: [
      { id: "investors", label: "Investors" },
      { id: "lenders", label: "Lenders" },
      { id: "board-of-directors", label: "Board of Directors" },
      { id: "business-partners", label: "Business Partners" },
      { id: "members-owners", label: "Members / Owners" },
      { id: "grantors-funding-organizations", label: "Grantors / Funding Organizations" },
      { id: "franchisor-parent-company", label: "Franchisor / Parent Company" },
      { id: "other", label: "Other", allowOtherText: true },
      { id: "no", label: "No" },
    ],
    order: 1,
    status: "active",
  },
  {
    id: "stakeholders.receivedFunding",
    categoryId: "stakeholders-investors-reporting",
    kind: "single-select",
    prompt: "Have you received capital, funding, or investment from any of your stakeholders?",
    showIf: {
      questionId: "stakeholders.types",
      equalsAny: [
        "investors",
        "lenders",
        "board-of-directors",
        "business-partners",
        "members-owners",
        "grantors-funding-organizations",
        "franchisor-parent-company",
        "other",
      ],
    },
    options: YES_NO,
    order: 2,
    status: "active",
  },
  {
    id: "stakeholders.hasReportingRequirements",
    categoryId: "stakeholders-investors-reporting",
    kind: "single-select",
    prompt: "Do you have reporting requirements to any of your stakeholders?",
    showIf: {
      questionId: "stakeholders.types",
      equalsAny: [
        "investors",
        "lenders",
        "board-of-directors",
        "business-partners",
        "members-owners",
        "grantors-funding-organizations",
        "franchisor-parent-company",
        "other",
      ],
    },
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" },
      { id: "not-sure", label: "I'm not sure" },
    ],
    order: 3,
    status: "active",
  },
  {
    id: "stakeholders.reportingContent",
    categoryId: "stakeholders-investors-reporting",
    kind: "multi-select",
    prompt: "What are you required to report?",
    showIf: { questionId: "stakeholders.hasReportingRequirements", equalsAny: ["yes"] },
    options: [
      { id: "financial-results", label: "Financial results" },
      { id: "revenue", label: "Revenue" },
      { id: "profit-loss", label: "Profit / Loss" },
      { id: "use-of-funds", label: "Use of funds" },
      { id: "business-performance", label: "Business performance" },
      { id: "milestones-goals", label: "Milestones / Goals" },
      { id: "progress-on-specific-projects", label: "Progress on specific projects" },
      { id: "other", label: "Other", allowOtherText: true },
    ],
    order: 4,
    status: "active",
  },
  {
    id: "stakeholders.reportingFrequency",
    categoryId: "stakeholders-investors-reporting",
    kind: "single-select",
    prompt: "How often do you report?",
    showIf: { questionId: "stakeholders.hasReportingRequirements", equalsAny: ["yes"] },
    options: [
      { id: "weekly", label: "Weekly" },
      { id: "monthly", label: "Monthly" },
      { id: "quarterly", label: "Quarterly" },
      { id: "twice-a-year", label: "Twice a year" },
      { id: "annually", label: "Annually" },
      { id: "as-needed-on-request", label: "As needed / on request" },
      { id: "other", label: "Other", allowOtherText: true },
    ],
    order: 5,
    status: "active",
  },
  {
    id: "stakeholders.reportingProblem",
    categoryId: "stakeholders-investors-reporting",
    kind: "multi-select",
    prompt: "Is stakeholder reporting currently creating a problem or concern for you?",
    showIf: { questionId: "stakeholders.hasReportingRequirements", equalsAny: ["yes"] },
    options: [
      { id: "no", label: "No" },
      { id: "takes-too-much-time", label: "Takes too much time" },
      { id: "difficult-to-prepare", label: "Difficult to prepare" },
      { id: "information-difficult-to-gather", label: "Information is difficult to gather" },
      { id: "reporting-inconsistent", label: "Reporting is inconsistent" },
      { id: "deadlines-difficult-to-meet", label: "Deadlines are difficult to meet" },
      { id: "have-to-do-it-myself", label: "I have to do it myself" },
      { id: "not-sure-what-stakeholders-need", label: "I'm not sure what stakeholders need" },
      { id: "other", label: "Other", allowOtherText: true },
    ],
    order: 6,
    status: "active",
  },
  {
    id: "stakeholders.ownership",
    categoryId: "stakeholders-investors-reporting",
    kind: "single-select",
    prompt: "Who currently owns stakeholder reporting?",
    showIf: {
      questionId: "stakeholders.types",
      equalsAny: [
        "investors",
        "lenders",
        "board-of-directors",
        "business-partners",
        "members-owners",
        "grantors-funding-organizations",
        "franchisor-parent-company",
        "other",
      ],
    },
    options: BBA_OWNERSHIP_OPTIONS,
    order: 7,
    status: "active",
  },
]

/* ===========================================================================
 * Helpers
 * ======================================================================== */

export function getCategoryQuestions(categoryId: string): BbaQuestion[] {
  return BBA_QUESTIONS.filter((q) => q.categoryId === categoryId && q.status === "active").sort(
    (a, b) => a.order - b.order,
  )
}

export function getOrderedCategories(): BbaCategory[] {
  return [...BBA_CATEGORIES].sort((a, b) => a.order - b.order)
}

/** True if a question with a `showIf` clause should currently render, given all responses so far. */
export function shouldShowQuestion(
  question: BbaQuestion,
  responses: Record<string, string | string[] | number>,
): boolean {
  if (!question.showIf) return true
  const value = responses[question.showIf.questionId]
  if (value === undefined) return false
  const values = Array.isArray(value) ? value : [String(value)]
  return values.some((v) => question.showIf!.equalsAny.includes(String(v)))
}
