/**
 * Work-Life Balance Boundary Library™ — seeded content catalog + relationships.
 *
 * Static, versioned content (no user data). The future Boundary Builder™ and
 * Recommendation Engine read from here. See ./types for the object model and
 * ./server for custom-boundary persistence + selector helpers.
 *
 * Design intent: relationships are MEANINGFUL, not exhaustive. Not every
 * boundary maps to every requirement/stakeholder — only where it is genuinely
 * relevant, so future logic can surface a small, contextual set of choices.
 */

import type {
  BoundaryFamily,
  BoundaryPattern,
  BusinessRequirement,
  EscalationPattern,
  ExceptionPattern,
  ImplementationRequirement,
  OperatingRulePattern,
  StakeholderRequirement,
  StakeholderType,
  TrainingRequirement,
} from "./types"

/* ------------------------------------------------------------------ */
/* A. Boundary Families                                                */
/* ------------------------------------------------------------------ */

export const BOUNDARY_FAMILIES: BoundaryFamily[] = [
  { id: "time", name: "Time", description: "Protected containers of time that belong to life, not the business.", sortOrder: 10 },
  { id: "availability", name: "Availability", description: "When the founder is — and is not — reachable by the business.", sortOrder: 20 },
  { id: "focus", name: "Focus", description: "Protected attention for deep, strategic, uninterrupted work.", sortOrder: 30 },
  { id: "communication", name: "Communication", description: "How and when business communication happens.", sortOrder: 40 },
  { id: "meetings", name: "Meetings", description: "What earns a meeting and how meetings are run.", sortOrder: 50 },
  { id: "decision-ownership", name: "Decision Ownership", description: "Who owns which decisions, and what actually needs the founder.", sortOrder: 60 },
  { id: "client", name: "Client", description: "How client work, access, and scope are contained.", sortOrder: 70 },
  { id: "team", name: "Team", description: "Ownership, coverage, and norms across the team.", sortOrder: 80 },
  { id: "workload-capacity", name: "Workload / Capacity", description: "Limits on how much work enters the system.", sortOrder: 90 },
  { id: "recovery-human", name: "Recovery / Human", description: "Protection for sleep, health, and restoration.", sortOrder: 100 },
  { id: "ai-automation", name: "AI / Automation", description: "Using automation and AI to make boundaries operationally possible.", sortOrder: 110 },
]

/* ------------------------------------------------------------------ */
/* D. Business Requirements                                            */
/* ------------------------------------------------------------------ */

export const BUSINESS_REQUIREMENTS: BusinessRequirement[] = [
  { id: "delegate", label: "Delegate", description: "Move ownership of work to someone else.", operatingRules: ["rule-decision-authority", "rule-client-followup-owner"] },
  { id: "eliminate", label: "Eliminate", description: "Stop doing work that does not need to happen.", operatingRules: ["rule-eliminate-recurring-meeting"] },
  { id: "automate", label: "Automate", description: "Let a system handle routine work without a person.", operatingRules: ["rule-automated-notifications", "rule-automated-scheduling"] },
  { id: "ai-augment", label: "AI-Augment", description: "Use AI to do first-pass or repetitive work.", operatingRules: ["rule-ai-first-pass", "rule-ai-triage"] },
  { id: "systematize", label: "Systematize", description: "Turn ad-hoc work into a repeatable documented process.", operatingRules: ["rule-documented-process"] },
  { id: "change-scheduling", label: "Change scheduling", description: "Change when work and meetings are scheduled.", operatingRules: ["rule-no-meetings-protected-time", "rule-automated-scheduling"] },
  { id: "change-meetings", label: "Change meetings", description: "Change what earns a meeting and how meetings run.", operatingRules: ["rule-meeting-standards", "rule-eliminate-recurring-meeting"] },
  { id: "change-communication-expectations", label: "Change communication expectations", description: "Reset when and how quickly communication is answered.", operatingRules: ["rule-comms-end-time", "rule-response-windows"] },
  { id: "change-client-expectations", label: "Change client expectations", description: "Reset client response, availability, and scope norms.", operatingRules: ["rule-client-response-window", "rule-client-revision-limit"] },
  { id: "reassign-decision-ownership", label: "Reassign decision ownership", description: "Give defined decisions to roles other than the founder.", operatingRules: ["rule-decision-authority", "rule-approval-threshold"] },
  { id: "create-coverage", label: "Create coverage", description: "Ensure someone covers work when the founder is unavailable.", operatingRules: ["rule-coverage-window"] },
  { id: "clarify-ownership", label: "Clarify ownership", description: "Make it explicit who owns what.", operatingRules: ["rule-documented-process"] },
  { id: "change-workload-capacity", label: "Change workload / capacity", description: "Cap or reprioritize how much work is taken on.", operatingRules: ["rule-wip-limit", "rule-reprioritization"] },
  { id: "create-escalation-coverage", label: "Create escalation coverage", description: "Define an escalation path so urgent matters do not default to the founder.", operatingRules: ["rule-escalation-path"] },
  { id: "document-process", label: "Document the process", description: "Write down how the work is done so others can own it.", operatingRules: ["rule-documented-process"] },
  { id: "create-backup-ownership", label: "Create backup ownership", description: "Name a backup owner for continuity.", operatingRules: ["rule-coverage-window", "rule-escalation-path"] },
  { id: "other-custom", label: "Other / custom", description: "A business change specific to this founder.", operatingRules: [] },
]

/* ------------------------------------------------------------------ */
/* E. Operating Rule Patterns                                          */
/* ------------------------------------------------------------------ */

export const OPERATING_RULE_PATTERNS: OperatingRulePattern[] = [
  {
    id: "rule-comms-end-time",
    category: "communication",
    name: "Business communication ends at a defined time",
    ruleText: "Routine business communication ends at 5:00 PM. Messages received after that time are handled during the next designated business communication window.",
    businessRequirements: ["change-communication-expectations", "automate"],
    implementationRequirements: ["change-notification-settings", "update-internal-docs", "set-effective-date"],
    sortOrder: 10,
  },
  {
    id: "rule-response-windows",
    category: "communication",
    name: "Defined response windows",
    ruleText: "Non-urgent messages are answered within defined response windows rather than immediately.",
    businessRequirements: ["change-communication-expectations"],
    implementationRequirements: ["update-internal-docs", "update-client-docs"],
    sortOrder: 20,
  },
  {
    id: "rule-decision-authority",
    category: "decision-ownership",
    name: "Routine decisions do not require founder approval",
    ruleText: "Routine decisions within the defined authority level do not require founder approval.",
    businessRequirements: ["reassign-decision-ownership", "delegate"],
    implementationRequirements: ["delegate-ownership", "update-sop", "obtain-approval", "set-effective-date"],
    sortOrder: 30,
  },
  {
    id: "rule-approval-threshold",
    category: "decision-ownership",
    name: "Founder approval only above a threshold",
    ruleText: "Only decisions above the defined threshold require founder approval; everything below is owned by the defined role.",
    businessRequirements: ["reassign-decision-ownership"],
    implementationRequirements: ["update-sop", "delegate-ownership"],
    sortOrder: 40,
  },
  {
    id: "rule-no-meetings-protected-time",
    category: "meetings",
    name: "No meetings during protected time",
    ruleText: "Meetings during protected CEO Workday™ time are reserved for defined exceptions only.",
    businessRequirements: ["change-scheduling", "change-meetings"],
    implementationRequirements: ["update-calendar", "update-scheduling-rules", "set-effective-date"],
    sortOrder: 50,
  },
  {
    id: "rule-meeting-standards",
    category: "meetings",
    name: "Agenda, owner, and outcome required",
    ruleText: "A meeting requires an agenda, an owner, and a defined outcome, or it does not happen.",
    businessRequirements: ["change-meetings"],
    implementationRequirements: ["update-internal-docs", "team-training"],
    sortOrder: 60,
  },
  {
    id: "rule-eliminate-recurring-meeting",
    category: "meetings",
    name: "Eliminate unnecessary recurring meetings",
    ruleText: "Recurring meetings without a current agenda, owner, and outcome are eliminated or replaced with an async update.",
    businessRequirements: ["eliminate", "change-meetings"],
    implementationRequirements: ["update-calendar", "team-training"],
    sortOrder: 70,
  },
  {
    id: "rule-client-response-window",
    category: "client",
    name: "Defined client response window",
    ruleText: "Client messages are answered within the defined response window during business hours; there is no routine after-hours client response.",
    businessRequirements: ["change-client-expectations"],
    implementationRequirements: ["update-client-docs", "client-meeting", "set-effective-date"],
    sortOrder: 80,
  },
  {
    id: "rule-client-revision-limit",
    category: "client",
    name: "Defined revision rounds",
    ruleText: "Client revisions are limited to the defined number of rounds; additional rounds follow the change process.",
    businessRequirements: ["change-client-expectations"],
    implementationRequirements: ["update-client-docs", "client-meeting"],
    sortOrder: 90,
  },
  {
    id: "rule-escalation-path",
    category: "decision-ownership",
    name: "Urgent matters follow an escalation path",
    ruleText: "Urgent matters follow the designated escalation path rather than defaulting to the founder.",
    businessRequirements: ["create-escalation-coverage", "create-backup-ownership"],
    implementationRequirements: ["delegate-ownership", "assign-backup", "team-training", "set-effective-date"],
    sortOrder: 100,
  },
  {
    id: "rule-coverage-window",
    category: "availability",
    name: "Coverage outside founder availability",
    ruleText: "Outside defined founder availability, the designated owner or backup handles matters within their authority.",
    businessRequirements: ["create-coverage", "create-backup-ownership"],
    implementationRequirements: ["assign-backup", "update-sop", "set-effective-date"],
    sortOrder: 110,
  },
  {
    id: "rule-automated-notifications",
    category: "ai-automation",
    name: "Automated notifications and reminders",
    ruleText: "Routine notifications and reminders are automated rather than sent manually by the founder.",
    businessRequirements: ["automate"],
    implementationRequirements: ["configure-automation", "change-notification-settings"],
    sortOrder: 120,
  },
  {
    id: "rule-automated-scheduling",
    category: "ai-automation",
    name: "Automated scheduling",
    ruleText: "Scheduling is handled by an automated system within defined availability rules.",
    businessRequirements: ["automate", "change-scheduling"],
    implementationRequirements: ["configure-automation", "update-scheduling-rules"],
    sortOrder: 130,
  },
  {
    id: "rule-ai-first-pass",
    category: "ai-automation",
    name: "AI handles first-pass work",
    ruleText: "AI produces the first pass of defined repetitive work; a person reviews and finalizes.",
    businessRequirements: ["ai-augment"],
    implementationRequirements: ["configure-ai-workflow", "test-period"],
    sortOrder: 140,
  },
  {
    id: "rule-ai-triage",
    category: "ai-automation",
    name: "AI-assisted triage",
    ruleText: "Incoming routine requests are triaged by AI and routed to the correct owner.",
    businessRequirements: ["ai-augment", "automate"],
    implementationRequirements: ["configure-ai-workflow", "test-period"],
    sortOrder: 150,
  },
  {
    id: "rule-documented-process",
    category: "team",
    name: "Documented process with clear ownership",
    ruleText: "The process is documented with a named owner so it no longer depends on the founder.",
    businessRequirements: ["document-process", "clarify-ownership", "systematize"],
    implementationRequirements: ["update-sop", "delegate-ownership", "team-training"],
    sortOrder: 160,
  },
  {
    id: "rule-wip-limit",
    category: "workload-capacity",
    name: "Work-in-progress limit",
    ruleText: "The number of active commitments is capped at the defined limit; new work waits until capacity frees up.",
    businessRequirements: ["change-workload-capacity"],
    implementationRequirements: ["update-sop", "set-review-date"],
    sortOrder: 170,
  },
  {
    id: "rule-reprioritization",
    category: "workload-capacity",
    name: "Reprioritization rule",
    ruleText: "When new work arrives at capacity, existing work is reprioritized or declined rather than simply added.",
    businessRequirements: ["change-workload-capacity"],
    implementationRequirements: ["update-sop", "set-review-date"],
    sortOrder: 180,
  },
]

/* ------------------------------------------------------------------ */
/* F. Implementation Requirements                                      */
/* ------------------------------------------------------------------ */

export const IMPLEMENTATION_REQUIREMENTS: ImplementationRequirement[] = [
  { id: "delegate-ownership", label: "Delegate ownership", description: "Assign a named owner for the work." },
  { id: "assign-backup", label: "Assign backup", description: "Name a backup owner for continuity." },
  { id: "update-sop", label: "Update SOP", description: "Update the standard operating procedure." },
  { id: "update-calendar", label: "Update calendar", description: "Reflect the boundary on the working calendar." },
  { id: "update-scheduling-rules", label: "Update scheduling rules", description: "Change scheduling logic or booking rules." },
  { id: "change-notification-settings", label: "Change notification settings", description: "Adjust notifications so they respect the boundary." },
  { id: "configure-automation", label: "Configure automation", description: "Set up the automated workflow." },
  { id: "configure-ai-workflow", label: "Configure AI workflow", description: "Set up the AI-assisted workflow." },
  { id: "update-client-docs", label: "Update client documentation", description: "Update client-facing docs and agreements." },
  { id: "update-internal-docs", label: "Update internal documentation", description: "Update internal-facing docs and norms." },
  { id: "team-training", label: "Create team training", description: "Prepare training for the team." },
  { id: "schedule-qa", label: "Schedule Q&A", description: "Schedule a question-and-answer session." },
  { id: "schedule-team-meeting", label: "Schedule team meeting", description: "Schedule a team meeting." },
  { id: "client-meeting", label: "Schedule client meeting", description: "Schedule a client meeting." },
  { id: "one-on-one", label: "Schedule one-on-one", description: "Schedule an individual conversation." },
  { id: "create-walkthrough", label: "Create walkthrough", description: "Prepare a walkthrough of the new process." },
  { id: "practice-period", label: "Create practice period", description: "Allow a period to practice the new rule." },
  { id: "test-period", label: "Create test period", description: "Run a test period before it is fully in force." },
  { id: "set-effective-date", label: "Set effective date", description: "Define when the rule takes effect." },
  { id: "set-review-date", label: "Set review date", description: "Define when the rule will be reviewed." },
  { id: "obtain-approval", label: "Obtain required approval", description: "Get any approval the change requires." },
]

/* ------------------------------------------------------------------ */
/* G. Escalation Patterns                                              */
/* ------------------------------------------------------------------ */

export const ESCALATION_PATTERNS: EscalationPattern[] = [
  {
    id: "esc-routine-client",
    name: "Routine client matter",
    trigger: "A client raises a routine matter outside founder availability.",
    channel: "Designated client channel",
    responseExpectation: "Within the defined client response window.",
    founderInvolvementThreshold: "Only above the defined severity or financial threshold.",
    levels: [
      { order: 1, role: "Client Success", responsibility: "Own and resolve routine client matters." },
      { order: 2, role: "Account Lead", responsibility: "Handle matters beyond Client Success authority." },
      { order: 3, role: "Operations", responsibility: "Coordinate cross-functional resolution." },
      { order: 4, role: "Founder", responsibility: "Engage only above the defined threshold." },
    ],
  },
  {
    id: "esc-team-operational",
    name: "Team operational issue",
    trigger: "A team member hits an operational blocker.",
    channel: "Internal escalation channel",
    responseExpectation: "Same business day.",
    founderInvolvementThreshold: "Exception only.",
    levels: [
      { order: 1, role: "Team Member", responsibility: "Attempt resolution within their authority." },
      { order: 2, role: "Manager", responsibility: "Resolve or reassign the issue." },
      { order: 3, role: "Operations", responsibility: "Handle systemic or cross-team issues." },
      { order: 4, role: "Founder", responsibility: "Engage as a defined exception only." },
    ],
  },
  {
    id: "esc-system-failure",
    name: "Business-critical system failure",
    trigger: "A system failure threatens business-critical operations.",
    channel: "Incident channel",
    responseExpectation: "Immediate acknowledgement per incident policy.",
    founderInvolvementThreshold: "Only if business-critical and unresolved at prior levels.",
    levels: [
      { order: 1, role: "System Owner", responsibility: "Diagnose and attempt recovery." },
      { order: 2, role: "Technical Backup", responsibility: "Support recovery if the owner is unavailable." },
      { order: 3, role: "Operations", responsibility: "Coordinate response and communication." },
      { order: 4, role: "Founder", responsibility: "Engage only if business-critical." },
    ],
  },
]

/* ------------------------------------------------------------------ */
/* H. Exception Patterns (exceptions AND explicit non-exceptions)      */
/* ------------------------------------------------------------------ */

export const EXCEPTION_PATTERNS: ExceptionPattern[] = [
  { id: "exc-safety", label: "Safety issue", isException: true, description: "A genuine safety concern for a person." },
  { id: "exc-legal", label: "Legal / regulatory issue", isException: true, description: "A legal or regulatory matter requiring prompt attention." },
  { id: "exc-critical-client", label: "Critical client issue", isException: true, description: "A critical, time-sensitive client issue." },
  { id: "exc-system-failure", label: "Business-critical system failure", isException: true, description: "A failure threatening business-critical operations." },
  { id: "exc-financial-threshold", label: "Defined financial threshold", isException: true, description: "A matter above a defined financial threshold." },
  { id: "exc-team-emergency", label: "Team emergency", isException: true, description: "A genuine team emergency." },
  { id: "exc-scheduled", label: "Scheduled exception", isException: true, description: "A pre-agreed, scheduled exception." },
  { id: "exc-other", label: "Other", isException: true, description: "Another genuine exception defined by the founder." },
  { id: "not-routine-client", label: "Routine client request", isException: false, description: "A normal client request is not an exception." },
  { id: "not-nonurgent-email", label: "Non-urgent email", isException: false, description: "A non-urgent email is not an exception." },
  { id: "not-routine-approval", label: "Routine approval", isException: false, description: "A routine approval is not an exception." },
  { id: "not-scheduling-question", label: "Normal scheduling question", isException: false, description: "A normal scheduling question is not an exception." },
  { id: "not-internal-question", label: "Routine internal question", isException: false, description: "A routine internal question is not an exception." },
  { id: "not-unfinished-work", label: "Work not completed during the work container", isException: false, description: "Work that simply was not finished during normal hours is not an exception." },
]

/* ------------------------------------------------------------------ */
/* I. Stakeholder Types + Requirements                                 */
/* ------------------------------------------------------------------ */

export const STAKEHOLDER_TYPES: StakeholderType[] = [
  { id: "founder", label: "Founder", description: "The founder themselves." },
  { id: "team-member", label: "Team Member", description: "An individual contributor on the team." },
  { id: "manager", label: "Manager / Leader", description: "A manager or team lead." },
  { id: "client", label: "Client", description: "A paying client." },
  { id: "partner", label: "Partner", description: "A business partner." },
  { id: "vendor", label: "Vendor", description: "A vendor or supplier." },
  { id: "investor", label: "Investor", description: "An investor." },
  { id: "shareholder", label: "Shareholder", description: "A shareholder." },
  { id: "board-member", label: "Board Member", description: "A member of the board." },
  { id: "advisor", label: "Advisor", description: "An advisor." },
  { id: "contractor", label: "Contractor", description: "A contractor." },
  { id: "family-personal", label: "Family / Personal Stakeholder", description: "A personal or family stakeholder." },
  { id: "other", label: "Other", description: "Another relevant stakeholder." },
]

export const STAKEHOLDER_REQUIREMENTS: StakeholderRequirement[] = [
  { id: "must-be-informed", label: "Must be informed", description: "Needs to be told about the boundary." },
  { id: "must-acknowledge", label: "Must acknowledge", description: "Needs to acknowledge the boundary." },
  { id: "must-approve", label: "Must approve", description: "Needs to approve the change." },
  { id: "must-change-behavior", label: "Must change behavior", description: "Needs to change how they act." },
  { id: "must-take-ownership", label: "Must take ownership", description: "Needs to own new work or decisions." },
  { id: "must-receive-training", label: "Must receive training", description: "Needs training on the new process." },
  { id: "must-attend-qa", label: "Must attend Q&A", description: "Needs to attend a Q&A session." },
  { id: "must-attend-meeting", label: "Must attend meeting", description: "Needs to attend a meeting." },
  { id: "must-understand-escalation", label: "Must understand escalation path", description: "Needs to understand the escalation path." },
  { id: "must-confirm-coverage", label: "Must confirm coverage", description: "Needs to confirm coverage arrangements." },
  { id: "must-confirm-effective-date", label: "Must confirm effective date", description: "Needs to confirm the effective date." },
]

/* ------------------------------------------------------------------ */
/* J. Training / Q&A / Follow-Up Requirements                          */
/* ------------------------------------------------------------------ */

export const TRAINING_REQUIREMENTS: TrainingRequirement[] = [
  { id: "none", label: "No additional support", description: "No additional support needed." },
  { id: "written-instructions", label: "Written instructions", description: "Written instructions are sufficient." },
  { id: "training-session", label: "Training session", description: "A dedicated training session is needed." },
  { id: "qa-session", label: "Q&A session", description: "A question-and-answer session is needed." },
  { id: "team-meeting", label: "Team meeting", description: "A team meeting is needed." },
  { id: "client-meeting", label: "Client meeting", description: "A client meeting is needed." },
  { id: "one-on-one", label: "One-on-one", description: "An individual conversation is needed." },
  { id: "walkthrough", label: "Walkthrough", description: "A guided walkthrough is needed." },
  { id: "demonstration", label: "Demonstration", description: "A demonstration is needed." },
  { id: "practice-period", label: "Practice period", description: "A practice period is needed." },
  { id: "test-period", label: "Test period", description: "A test period is needed." },
  { id: "follow-up-meeting", label: "Follow-up meeting", description: "A follow-up meeting is needed." },
  { id: "confirmation-checkpoint", label: "Confirmation checkpoint", description: "A confirmation checkpoint is needed." },
]

/* ------------------------------------------------------------------ */
/* B. Boundary Patterns (seeded across every family)                   */
/* ------------------------------------------------------------------ */

export const BOUNDARY_PATTERNS: BoundaryPattern[] = [
  /* ---- TIME ---- */
  {
    id: "protect-evening",
    family: "time",
    name: "Protect My Evenings From Routine Business Activity",
    shortDescription: "Evenings belong to life, not routine business activity.",
    boundaryStatement: "Routine business activity does not enter my protected evening.",
    bestFor: "Founders whose evenings are consumed by after-hours work and messages.",
    possibleLifePriorities: ["family", "partner", "rest", "home"],
    relatedRealityCheckSignals: ["frequent-evening-work", "after-hours-availability", "high-relationship-priority", "high-family-priority"],
    relatedBusinessRealitySignals: ["after-hours-communication", "founder-approval-dependency", "no-coverage"],
    businessRequirements: ["change-communication-expectations", "delegate", "create-coverage", "reassign-decision-ownership", "automate", "create-escalation-coverage"],
    operatingRules: ["rule-comms-end-time", "rule-decision-authority", "rule-coverage-window", "rule-escalation-path", "rule-automated-notifications"],
    escalationPatterns: ["esc-routine-client", "esc-team-operational"],
    exceptionPatterns: ["exc-safety", "exc-critical-client", "exc-system-failure", "not-routine-client", "not-nonurgent-email"],
    stakeholderTypes: ["team-member", "manager", "client", "family-personal"],
    active: true,
    sortOrder: 10,
  },
  {
    id: "protect-weekend",
    family: "time",
    name: "Protect My Weekend",
    shortDescription: "Weekends are not a routine work overflow.",
    boundaryStatement: "My weekend is not a routine extension of the business.",
    bestFor: "Founders whose weekends are routinely absorbed by work.",
    possibleLifePriorities: ["family", "rest", "recreation", "friends", "travel"],
    relatedRealityCheckSignals: ["frequent-weekend-work", "always-on", "low-recovery", "high-rest-priority"],
    relatedBusinessRealitySignals: ["no-coverage", "founder-approval-dependency", "reactive-communication"],
    businessRequirements: ["create-coverage", "reassign-decision-ownership", "create-escalation-coverage", "change-communication-expectations"],
    operatingRules: ["rule-coverage-window", "rule-decision-authority", "rule-escalation-path", "rule-comms-end-time"],
    escalationPatterns: ["esc-routine-client", "esc-system-failure"],
    exceptionPatterns: ["exc-safety", "exc-system-failure", "exc-scheduled", "not-routine-client", "not-unfinished-work"],
    stakeholderTypes: ["team-member", "manager", "client"],
    active: true,
    sortOrder: 20,
  },
  {
    id: "defined-workday-end",
    family: "time",
    name: "Defined Workday End",
    shortDescription: "The workday has a real, defined end.",
    boundaryStatement: "My workday ends at a defined time and business activity stops.",
    bestFor: "Founders with no clear line between work and life.",
    possibleLifePriorities: ["family", "rest", "movement", "home"],
    relatedRealityCheckSignals: ["no-defined-workday", "frequent-evening-work", "always-on"],
    relatedBusinessRealitySignals: ["after-hours-communication", "reactive-communication"],
    businessRequirements: ["change-communication-expectations", "create-coverage", "automate"],
    operatingRules: ["rule-comms-end-time", "rule-coverage-window", "rule-automated-notifications"],
    escalationPatterns: ["esc-team-operational"],
    exceptionPatterns: ["exc-critical-client", "exc-system-failure", "not-unfinished-work", "not-nonurgent-email"],
    stakeholderTypes: ["team-member", "manager", "client"],
    active: true,
    sortOrder: 30,
  },
  {
    id: "protect-lunch",
    family: "time",
    name: "Protected Lunch",
    shortDescription: "A real break in the middle of the day.",
    boundaryStatement: "My lunch break is protected and not scheduled over.",
    bestFor: "Founders who work straight through every day.",
    possibleLifePriorities: ["rest", "movement"],
    relatedRealityCheckSignals: ["low-recovery", "high-health-priority", "interrupted-focus"],
    relatedBusinessRealitySignals: ["high-meeting-load"],
    businessRequirements: ["change-scheduling"],
    operatingRules: ["rule-no-meetings-protected-time", "rule-automated-scheduling"],
    escalationPatterns: [],
    exceptionPatterns: ["exc-scheduled", "not-scheduling-question"],
    stakeholderTypes: ["team-member", "manager"],
    active: true,
    sortOrder: 40,
  },

  /* ---- AVAILABILITY ---- */
  {
    id: "no-afterhours-availability",
    family: "availability",
    name: "No Routine After-Hours Availability",
    shortDescription: "The founder is not routinely reachable after hours.",
    boundaryStatement: "I am not routinely available to the business after hours.",
    bestFor: "Founders who are the default contact at all hours.",
    possibleLifePriorities: ["family", "partner", "rest"],
    relatedRealityCheckSignals: ["after-hours-availability", "always-on", "founder-dependency"],
    relatedBusinessRealitySignals: ["no-coverage", "no-escalation-path", "founder-approval-dependency"],
    businessRequirements: ["create-coverage", "create-escalation-coverage", "reassign-decision-ownership", "create-backup-ownership"],
    operatingRules: ["rule-coverage-window", "rule-escalation-path", "rule-decision-authority"],
    escalationPatterns: ["esc-routine-client", "esc-team-operational", "esc-system-failure"],
    exceptionPatterns: ["exc-safety", "exc-system-failure", "exc-critical-client", "not-routine-client", "not-nonurgent-email"],
    stakeholderTypes: ["team-member", "manager", "client", "partner"],
    active: true,
    sortOrder: 10,
  },
  {
    id: "defined-response-windows",
    family: "availability",
    name: "Defined Response Windows",
    shortDescription: "Responses happen in windows, not instantly.",
    boundaryStatement: "I respond within defined windows rather than immediately.",
    bestFor: "Founders trapped in real-time reactivity.",
    possibleLifePriorities: ["rest", "family"],
    relatedRealityCheckSignals: ["always-on", "interrupted-focus"],
    relatedBusinessRealitySignals: ["reactive-communication", "after-hours-communication"],
    businessRequirements: ["change-communication-expectations", "automate"],
    operatingRules: ["rule-response-windows", "rule-automated-notifications"],
    escalationPatterns: ["esc-team-operational"],
    exceptionPatterns: ["exc-critical-client", "not-nonurgent-email"],
    stakeholderTypes: ["team-member", "client"],
    active: true,
    sortOrder: 20,
  },

  /* ---- FOCUS ---- */
  {
    id: "meeting-free-ceo-workday",
    family: "focus",
    name: "Meeting-Free CEO Workday™",
    shortDescription: "Protected time for CEO-level work.",
    boundaryStatement: "My CEO Workday™ is protected from routine meetings.",
    bestFor: "Founders buried in meetings with no time to lead.",
    possibleLifePriorities: ["personal-project", "learning", "creativity"],
    relatedRealityCheckSignals: ["interrupted-focus", "no-defined-workday"],
    relatedBusinessRealitySignals: ["high-meeting-load", "reactive-communication"],
    businessRequirements: ["change-scheduling", "change-meetings", "eliminate"],
    operatingRules: ["rule-no-meetings-protected-time", "rule-eliminate-recurring-meeting", "rule-meeting-standards"],
    escalationPatterns: ["esc-team-operational"],
    exceptionPatterns: ["exc-scheduled", "exc-critical-client", "not-scheduling-question", "not-internal-question"],
    stakeholderTypes: ["team-member", "manager"],
    active: true,
    sortOrder: 10,
  },
  {
    id: "protected-deep-work",
    family: "focus",
    name: "Protected Deep Work",
    shortDescription: "Uninterrupted blocks for deep work.",
    boundaryStatement: "My deep-work blocks are protected from routine interruptions.",
    bestFor: "Founders who cannot get uninterrupted time.",
    possibleLifePriorities: ["personal-project", "creativity", "learning"],
    relatedRealityCheckSignals: ["interrupted-focus"],
    relatedBusinessRealitySignals: ["high-meeting-load", "reactive-communication"],
    businessRequirements: ["change-scheduling", "change-communication-expectations", "automate"],
    operatingRules: ["rule-no-meetings-protected-time", "rule-response-windows", "rule-automated-notifications"],
    escalationPatterns: ["esc-team-operational"],
    exceptionPatterns: ["exc-critical-client", "not-internal-question", "not-nonurgent-email"],
    stakeholderTypes: ["team-member", "manager"],
    active: true,
    sortOrder: 20,
  },

  /* ---- COMMUNICATION ---- */
  {
    id: "comms-end-at-defined-time",
    family: "communication",
    name: "Business Communication Ends At A Defined Time",
    shortDescription: "Communication has a defined daily end.",
    boundaryStatement: "Business communication ends at a defined time each day.",
    bestFor: "Founders whose inbox never closes.",
    possibleLifePriorities: ["family", "rest", "partner"],
    relatedRealityCheckSignals: ["after-hours-communication", "always-on", "frequent-evening-work"],
    relatedBusinessRealitySignals: ["after-hours-communication", "reactive-communication"],
    businessRequirements: ["change-communication-expectations", "automate", "create-coverage"],
    operatingRules: ["rule-comms-end-time", "rule-response-windows", "rule-automated-notifications"],
    escalationPatterns: ["esc-routine-client", "esc-team-operational"],
    exceptionPatterns: ["exc-critical-client", "exc-system-failure", "not-nonurgent-email", "not-internal-question"],
    stakeholderTypes: ["team-member", "manager", "client"],
    active: true,
    sortOrder: 10,
  },
  {
    id: "escalation-only-urgent-comms",
    family: "communication",
    name: "Escalation-Only Urgent Communication",
    shortDescription: "Urgent means escalation path, not founder DM.",
    boundaryStatement: "Urgent matters use the escalation path, not a direct message to me.",
    bestFor: "Founders who are everyone's urgent contact.",
    possibleLifePriorities: ["rest", "family"],
    relatedRealityCheckSignals: ["founder-dependency", "always-on"],
    relatedBusinessRealitySignals: ["no-escalation-path", "founder-approval-dependency"],
    businessRequirements: ["create-escalation-coverage", "create-backup-ownership", "reassign-decision-ownership"],
    operatingRules: ["rule-escalation-path", "rule-decision-authority"],
    escalationPatterns: ["esc-routine-client", "esc-team-operational", "esc-system-failure"],
    exceptionPatterns: ["exc-safety", "exc-system-failure", "not-nonurgent-email"],
    stakeholderTypes: ["team-member", "manager", "client"],
    active: true,
    sortOrder: 20,
  },

  /* ---- MEETINGS ---- */
  {
    id: "meeting-standards",
    family: "meetings",
    name: "Agenda / Owner / Outcome Required",
    shortDescription: "Every meeting must earn its place.",
    boundaryStatement: "A meeting requires an agenda, an owner, and an outcome or it does not happen.",
    bestFor: "Founders drowning in low-value meetings.",
    possibleLifePriorities: ["personal-project"],
    relatedRealityCheckSignals: ["interrupted-focus"],
    relatedBusinessRealitySignals: ["high-meeting-load"],
    businessRequirements: ["change-meetings", "eliminate"],
    operatingRules: ["rule-meeting-standards", "rule-eliminate-recurring-meeting"],
    escalationPatterns: [],
    exceptionPatterns: ["exc-scheduled", "not-internal-question"],
    stakeholderTypes: ["team-member", "manager"],
    active: true,
    sortOrder: 10,
  },
  {
    id: "eliminate-recurring-meetings",
    family: "meetings",
    name: "Eliminate Unnecessary Recurring Meetings",
    shortDescription: "Kill standing meetings that no longer earn their slot.",
    boundaryStatement: "Recurring meetings without a current purpose are eliminated.",
    bestFor: "Founders with a calendar full of legacy standing meetings.",
    possibleLifePriorities: ["personal-project"],
    relatedRealityCheckSignals: ["interrupted-focus"],
    relatedBusinessRealitySignals: ["high-meeting-load"],
    businessRequirements: ["eliminate", "change-meetings"],
    operatingRules: ["rule-eliminate-recurring-meeting"],
    escalationPatterns: [],
    exceptionPatterns: ["not-internal-question"],
    stakeholderTypes: ["team-member", "manager"],
    active: true,
    sortOrder: 20,
  },

  /* ---- DECISION OWNERSHIP ---- */
  {
    id: "delegate-defined-decisions",
    family: "decision-ownership",
    name: "Delegate Defined Decisions",
    shortDescription: "Routine decisions do not need the founder.",
    boundaryStatement: "Defined routine decisions are owned by others, not me.",
    bestFor: "Founders who are the approval bottleneck.",
    possibleLifePriorities: ["rest", "personal-project"],
    relatedRealityCheckSignals: ["founder-dependency", "founder-approval-dependency"],
    relatedBusinessRealitySignals: ["founder-approval-dependency", "unclear-ownership", "low-team-ownership"],
    businessRequirements: ["reassign-decision-ownership", "delegate", "clarify-ownership", "document-process"],
    operatingRules: ["rule-decision-authority", "rule-approval-threshold", "rule-documented-process"],
    escalationPatterns: ["esc-team-operational"],
    exceptionPatterns: ["exc-financial-threshold", "not-routine-approval"],
    stakeholderTypes: ["team-member", "manager"],
    active: true,
    sortOrder: 10,
  },
  {
    id: "approval-threshold",
    family: "decision-ownership",
    name: "Founder Approval Threshold",
    shortDescription: "Only above a threshold does it reach the founder.",
    boundaryStatement: "Only decisions above the defined threshold require my approval.",
    bestFor: "Founders asked to approve everything.",
    possibleLifePriorities: ["rest"],
    relatedRealityCheckSignals: ["founder-approval-dependency"],
    relatedBusinessRealitySignals: ["founder-approval-dependency", "unclear-ownership"],
    businessRequirements: ["reassign-decision-ownership", "clarify-ownership"],
    operatingRules: ["rule-approval-threshold", "rule-decision-authority"],
    escalationPatterns: ["esc-team-operational"],
    exceptionPatterns: ["exc-financial-threshold", "not-routine-approval"],
    stakeholderTypes: ["team-member", "manager"],
    active: true,
    sortOrder: 20,
  },

  /* ---- CLIENT ---- */
  {
    id: "client-response-window",
    family: "client",
    name: "Defined Client Response Window",
    shortDescription: "Clients are answered in defined hours.",
    boundaryStatement: "Clients are answered within a defined window during business hours.",
    bestFor: "Founders answering clients at all hours.",
    possibleLifePriorities: ["family", "rest"],
    relatedRealityCheckSignals: ["after-hours-availability", "after-hours-communication"],
    relatedBusinessRealitySignals: ["client-scope-volatility", "reactive-communication", "after-hours-communication"],
    businessRequirements: ["change-client-expectations", "create-coverage", "delegate"],
    operatingRules: ["rule-client-response-window", "rule-coverage-window"],
    escalationPatterns: ["esc-routine-client"],
    exceptionPatterns: ["exc-critical-client", "not-routine-client", "not-nonurgent-email"],
    stakeholderTypes: ["client", "team-member", "manager"],
    active: true,
    sortOrder: 10,
  },
  {
    id: "client-revision-limit",
    family: "client",
    name: "Defined Revision Rounds",
    shortDescription: "Scope and revisions are contained.",
    boundaryStatement: "Client revisions are limited to the defined number of rounds.",
    bestFor: "Founders with runaway scope and endless revisions.",
    possibleLifePriorities: ["rest", "personal-project"],
    relatedRealityCheckSignals: ["always-on"],
    relatedBusinessRealitySignals: ["client-scope-volatility", "capacity-overload"],
    businessRequirements: ["change-client-expectations", "systematize", "document-process"],
    operatingRules: ["rule-client-revision-limit", "rule-documented-process"],
    escalationPatterns: ["esc-routine-client"],
    exceptionPatterns: ["exc-scheduled", "not-routine-client"],
    stakeholderTypes: ["client", "manager"],
    active: true,
    sortOrder: 20,
  },

  /* ---- TEAM ---- */
  {
    id: "team-ownership-clarity",
    family: "team",
    name: "Ownership Clarity",
    shortDescription: "Everyone knows who owns what.",
    boundaryStatement: "Every recurring responsibility has one clear owner who is not me by default.",
    bestFor: "Founders who are the fallback owner of everything.",
    possibleLifePriorities: ["rest"],
    relatedRealityCheckSignals: ["founder-dependency"],
    relatedBusinessRealitySignals: ["unclear-ownership", "low-team-ownership", "no-coverage"],
    businessRequirements: ["clarify-ownership", "delegate", "document-process", "create-backup-ownership"],
    operatingRules: ["rule-documented-process", "rule-decision-authority", "rule-coverage-window"],
    escalationPatterns: ["esc-team-operational"],
    exceptionPatterns: ["not-internal-question", "not-routine-approval"],
    stakeholderTypes: ["team-member", "manager"],
    active: true,
    sortOrder: 10,
  },
  {
    id: "team-afterhours-expectations",
    family: "team",
    name: "After-Hours Expectations",
    shortDescription: "The team is not expected to be always-on either.",
    boundaryStatement: "The team is not expected to be routinely available after hours.",
    bestFor: "Founders modeling always-on behavior for the team.",
    possibleLifePriorities: ["family", "rest"],
    relatedRealityCheckSignals: ["always-on", "after-hours-communication"],
    relatedBusinessRealitySignals: ["after-hours-communication", "reactive-communication"],
    businessRequirements: ["change-communication-expectations", "create-coverage", "create-escalation-coverage"],
    operatingRules: ["rule-comms-end-time", "rule-coverage-window", "rule-escalation-path"],
    escalationPatterns: ["esc-team-operational"],
    exceptionPatterns: ["exc-system-failure", "not-nonurgent-email"],
    stakeholderTypes: ["team-member", "manager"],
    active: true,
    sortOrder: 20,
  },

  /* ---- WORKLOAD / CAPACITY ---- */
  {
    id: "wip-limit",
    family: "workload-capacity",
    name: "Work-In-Progress Limit",
    shortDescription: "A cap on active commitments.",
    boundaryStatement: "Active commitments are capped at a defined limit.",
    bestFor: "Founders whose plate always expands.",
    possibleLifePriorities: ["rest", "personal-project"],
    relatedRealityCheckSignals: ["always-on", "low-recovery"],
    relatedBusinessRealitySignals: ["capacity-overload", "high-repetitive-workload"],
    businessRequirements: ["change-workload-capacity", "systematize"],
    operatingRules: ["rule-wip-limit", "rule-reprioritization"],
    escalationPatterns: [],
    exceptionPatterns: ["exc-scheduled", "not-unfinished-work"],
    stakeholderTypes: ["manager", "team-member"],
    active: true,
    sortOrder: 10,
  },
  {
    id: "stop-doing-rule",
    family: "workload-capacity",
    name: "Stop-Doing Rule",
    shortDescription: "New work means something else stops.",
    boundaryStatement: "When new work is added at capacity, something else is stopped or reprioritized.",
    bestFor: "Founders who only ever add, never remove.",
    possibleLifePriorities: ["rest"],
    relatedRealityCheckSignals: ["always-on"],
    relatedBusinessRealitySignals: ["capacity-overload"],
    businessRequirements: ["change-workload-capacity", "eliminate"],
    operatingRules: ["rule-reprioritization", "rule-wip-limit"],
    escalationPatterns: [],
    exceptionPatterns: ["not-unfinished-work"],
    stakeholderTypes: ["manager"],
    active: true,
    sortOrder: 20,
  },

  /* ---- RECOVERY / HUMAN ---- */
  {
    id: "power-down",
    family: "recovery-human",
    name: "Power Down™",
    shortDescription: "A defined end-of-day shutdown.",
    boundaryStatement: "I power down from the business at a defined time and do not restart.",
    bestFor: "Founders who never fully switch off.",
    possibleLifePriorities: ["rest", "family", "partner"],
    relatedRealityCheckSignals: ["frequent-evening-work", "low-recovery", "always-on", "high-rest-priority"],
    relatedBusinessRealitySignals: ["after-hours-communication", "no-coverage"],
    businessRequirements: ["change-communication-expectations", "create-coverage", "create-escalation-coverage", "automate"],
    operatingRules: ["rule-comms-end-time", "rule-coverage-window", "rule-escalation-path", "rule-automated-notifications"],
    escalationPatterns: ["esc-team-operational", "esc-system-failure"],
    exceptionPatterns: ["exc-safety", "exc-system-failure", "not-unfinished-work", "not-nonurgent-email"],
    stakeholderTypes: ["team-member", "manager", "client", "family-personal"],
    active: true,
    sortOrder: 10,
  },
  {
    id: "sleep-protection",
    family: "recovery-human",
    name: "Sleep Protection",
    shortDescription: "Sleep is not negotiable with the business.",
    boundaryStatement: "My sleep window is protected from business activity.",
    bestFor: "Founders sacrificing sleep for work.",
    possibleLifePriorities: ["rest", "movement"],
    relatedRealityCheckSignals: ["low-recovery", "always-on", "high-health-priority"],
    relatedBusinessRealitySignals: ["after-hours-communication", "no-escalation-path"],
    businessRequirements: ["change-communication-expectations", "create-escalation-coverage"],
    operatingRules: ["rule-comms-end-time", "rule-escalation-path"],
    escalationPatterns: ["esc-system-failure"],
    exceptionPatterns: ["exc-safety", "exc-system-failure", "not-nonurgent-email"],
    stakeholderTypes: ["team-member", "manager"],
    active: true,
    sortOrder: 20,
  },
  {
    id: "health-appointment-protection",
    family: "recovery-human",
    name: "Health Appointment Protection",
    shortDescription: "Health appointments are protected time.",
    boundaryStatement: "Health and personal appointments are protected and not overridden by work.",
    bestFor: "Founders who cancel health appointments for work.",
    possibleLifePriorities: ["movement", "rest"],
    relatedRealityCheckSignals: ["high-health-priority", "low-recovery"],
    relatedBusinessRealitySignals: ["high-meeting-load"],
    businessRequirements: ["change-scheduling", "create-coverage"],
    operatingRules: ["rule-no-meetings-protected-time", "rule-coverage-window"],
    escalationPatterns: [],
    exceptionPatterns: ["exc-scheduled", "not-scheduling-question"],
    stakeholderTypes: ["team-member", "manager"],
    active: true,
    sortOrder: 30,
  },

  /* ---- AI / AUTOMATION ---- */
  {
    id: "automate-routine-communication",
    family: "ai-automation",
    name: "Automate Routine Communication",
    shortDescription: "Routine messages send themselves.",
    boundaryStatement: "Routine communication is automated rather than sent by me.",
    bestFor: "Founders manually sending repetitive updates.",
    possibleLifePriorities: ["rest", "personal-project"],
    relatedRealityCheckSignals: ["always-on"],
    relatedBusinessRealitySignals: ["high-repetitive-workload", "reactive-communication"],
    businessRequirements: ["automate", "systematize"],
    operatingRules: ["rule-automated-notifications", "rule-automated-scheduling"],
    escalationPatterns: [],
    exceptionPatterns: ["not-nonurgent-email"],
    stakeholderTypes: ["team-member"],
    active: true,
    sortOrder: 10,
  },
  {
    id: "ai-first-pass-work",
    family: "ai-automation",
    name: "AI Handles First-Pass Work",
    shortDescription: "AI drafts, a person finalizes.",
    boundaryStatement: "AI produces the first pass of defined repetitive work.",
    bestFor: "Founders doing repetitive first-draft work themselves.",
    possibleLifePriorities: ["personal-project", "rest"],
    relatedRealityCheckSignals: ["always-on"],
    relatedBusinessRealitySignals: ["high-repetitive-workload", "capacity-overload"],
    businessRequirements: ["ai-augment", "systematize"],
    operatingRules: ["rule-ai-first-pass", "rule-ai-triage"],
    escalationPatterns: [],
    exceptionPatterns: ["exc-scheduled"],
    stakeholderTypes: ["team-member", "manager"],
    active: true,
    sortOrder: 20,
  },
]
